# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: About
    url: /about/
    weight: 20
  - name: Services
    url: /services/
    weight: 30
  - name: Use Cases
    url: /use-cases/
    weight: 40
  - name: Blog
    url: /blog/
    weight: 45
  - name: Contact
    url: /contact/
    weight: 50
