# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: indigo

# SEO
marketing:
  seo:
    site_type: Organization
    local_business_type: 'Software Development'
    org_name: 'Setu Geo Spatial Software Technologies'
    description: 'AI-enabled geospatial intelligence solutions for Indian government agencies and enterprises. Custom GIS development, drone mapping, and spatial analytics for data-driven decision making.'
    twitter: 'SetuGeoSpatial'
    # Open Graph / Facebook
    image: 'icon.svg'  # Default OG image (1200x630px recommended)
    # Twitter Card
    twitter_card: 'summary_large_image'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Favicon
favicon:
  icon: 'icon.svg'
  icon_pack: 'emoji'

# Site header
header:
  navbar:
    enable: true
    block: 'navbar'
    align: 'center'
    fixed_to_top: true
    logo:
      text: 'Setu Geo Spatial'
      # Logo filename in `assets/media/` folder
      filename: 'logo.svg'
    button:
      enable: true
      text: 'Request Demo'
      url: '/contact/'
    show_search: true
    show_theme_chooser: true

# Site footer
footer:
  copyright:
    notice: '© {year} Setu Geo Spatial Software Technologies'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Custom JavaScript
plugins:
  js:
    - path: 'js/sticky-cta.js'
